CREATE TABLE insured_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    content TEXT NOT NULL,
    content URL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);