CREATE TABLE insured_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    content TEXT NOT NULL,
    link URL,
    pol TEXT NOT NULL,
    catagory TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);